#!/usr/bin/env bash
# Fixes server bug
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen\s*([0-9a-fA-F\[\]:]*:)?80)/listen 8080/' /etc/nginx/sites-enabled/default
pkill apache2
# restart
su nginx -s /bin/bash -c 'service nginx restart
