#!/usr/bin/env bash
# Nginx should be running as the nginx user
# nginx must be listening on all active IPs on port 8080
# You cannot use apt-get remove

chown nginx /etc/nginx/nginx.conf
chmod u+r /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
