#!/usr/bin/env bash
# Fixes server bug
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen\s\+80;/listen 8080;/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
