#!/usr/bin/env bash
# Nginx should be running as the nginx user and listening on port 8080
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen\s\+80;/listen 8080;/' /etc/nginx/sites-available/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
